### ISSUE TITLE
Installation instructions can be clarified

### ISSUE THREAD

**Issue by DieterDePaepe** [tdt/docs#36]
I came across the following dificulties when following the instructions for TDT 5.6. This was on a fresh Ubuntu 14.04.2 x64.

- `pecl` is not available by default, resolved by `apt-get install php-pear`
- `php5enmod dbase` failed: `WARNING: Module dbase ini file doesn't exist under /etc/php5/mods-available`. Resolved by creating a file `/etc/php5/mods-available/dbase.ini` with content `extension=dbase.so` before running the command.
- `git` is not available by default, resolved by `apt-get install git`
- `composer install` fails due to missing mysql driver, resolved by `apt-get install php5-mysql`
- The installation location is not explicitely specified. Furthermore, the suggested apache configuration suggests `/var/www/core`, while the logging configuration suggests `/var/www/tdt`.

**Comment by coreation** [comment]
Hi @DieterDePaepe , thanks for the feedback!

I added the dbase PHP extension to our docs, need to get that working on our demo instance as well. (but it'll take a while because our Linux distro is EOL)
Pecl is the extension manager for PHP, so by adding the dbase extension, that also implies a pecl dependency, moreover it's a dependency to install an extension, but not necessary by tdt/core.

Git is listed as a dependency in the 5.6 docs, in the installation section. Can you link me to where you checked the dependencies?

The installation location is not specified because it's entirely up to the person that's installing it. Git clone will choose a name for you, but you can install it in whatever folder you feel like. I agree that choosing "tdt" as a folder in our docs might be somewhat confusing, but I don't think it's that much of a hassle?

**Comment by DieterDePaepe** [comment]
Hi, you're welcome!

Git is indeed listed, but not present in the apt-get command: http://docs.thedatatank.com/5.6/installation.

I am still a learning linux user, and it often confuses me in installation descriptions where I can safely dump my files to get things working. At first I just placed everything in my home folder, until I saw I should use the /var/www folder. Depends on how dummy proof you want to make your installation guide. ;)

**Comment by coreation** [comment]
Aha, that make sense now. Our installation folder isn't that dummy proof, but as you go using linux, you'll find that these instructions are quite default :).

**Comment by coreation** [comment]
Can you try publishing the demo data? Using this command: php artisan db:seed --class=DemoDataSeeder

That should seed some default datasets into your installation and amongst them a shp file. Then go to the JSON output of that dataset and see if you see osm_id amongst the fields.

**Comment by DieterDePaepe** [comment]
Both shape files have the osm_id field in the json output.

**Comment by coreation** [comment]
Let's continue [here](https://github.com/tdt/core/issues/315).
